[package]
name = "template-switch-statistics"
description = "Compute statistics for experiments with tsalign"
license = "BSD-2-Clause"
authors = ["Sebastian Schmidt <sebastian.schmidt@helsinki.fi>"]
repository = "https://github.com/sebschmi/template-switch-statistics"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"
lib_tsalign = { version = "0.3.4", features = ["serde"] }
plotters = "0.3.7"
