[package]
name = "template-switch-statistics"
description = "Compute statistics for experiments with tsalign"
license = "BSD-2-Clause"
authors = ["Sebastian Schmidt <sebastian.schmidt@helsinki.fi>"]
repository = "https://github.com/sebschmi/template-switch-statistics"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
lib_tsalign = { version = "0.8.9", features = ["serde"] }
plotters = { version = "0.3.7", git = "https://github.com/sebschmi/plotters", branch = "master", default-features = false, features = [
    "svg_backend",
    "all_elements",
    "all_series",
] }
noisy_float = { version = "0.2.0", features = ["serde"] }
log = "0.4.25"
simplelog = "0.12.2"
strum = { version = "0.26.3", features = ["derive"] }
