alignment = [[52, "Match"], [10, { TemplateSwitchEntrance = { primary = "Query", secondary = "Reference", first_offset = -9 } }], [13, "Match"], [2, { TemplateSwitchExit = { length_difference = 1 } }], [34, "Match"]]
cost = 0
cost_per_base = 0.0
duration_seconds = 0.000546915
opened_nodes = 2137
closed_nodes = 711
suboptimal_opened_nodes = 82
suboptimal_opened_nodes_ratio = 0.03990267639902676
test_sequence_name = "single_ts_0"
length = 100
seed = 0
alignment_config = "default"
ts_node_ord_strategy = "anti-diagonal"
ts_min_length_strategy = "lookahead"
template_switch_amount = 4